spring:
  h2:
    console:
      enabled: true
      path: /h2
#      settings:
#        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create-drop
server:
  servlet:
    encoding:
      force-response: true