jwt:
  secret: Y29kZXN0YXRlcy1wcmUtcHJvamVjdC10ZWFtLTQ1LWJvYXJkLXNlcnZpY2UtcmVhY3Qtd2l0aC1zcHJpbmctYm9vdC1zZWNyZXQta2V5Cg==
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: romchanxx@gmail.com
    password: gleaoglbojprmcly
    properties:
      mail:
#         debug: true
        smtp:
          auth: true
          starttls:
            enable: true